version: '3'
services:
  postgres:
    container_name: app_db
    image: postgres
    environment:
      POSTGRES_USER: warehouse_service
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
